plugins:
  - uses:
    - plugin: "http://localhost:4000"
      runsOn: [ "issues.labeled", "issues.unlabeled" ]
      with:
        labels:
          time:
            - "Time: <1 Hour"
            - "Time: <2 Hours"
            - "Time: <4 Hours"
            - "Time: <1 Day"
            - "Time: <1 Week"
          priority:
            - "Priority: 1 (Normal)"
            - "Priority: 2 (Medium)"
            - "Priority: 3 (High)"
            - "Priority: 4 (Urgent)"
            - "Priority: 5 (Emergency)"
        basePriceMultiplier: 1
        publicAccessControl:
          setLabel: true
          fundExternalClosedIssue: false
  - uses:
    - plugin: EresDevOrg/conversation-rewards-2
      runsOn: [ "issues.closed" ]
      with:
        evmNetworkId: 100
        evmPrivateEncrypted: "YU-tFJFczN3JPVoJu0pQKSbWoeiCFPjKiTXMoFnJxDDxUNX-BBXc6ZHkcQcHVjdOd6ZcEnU1o2jU3F-i05mGJPmhF2rhQYXkNlxu5U5fZMMcgxJ9INhAmktzRBUxWncg4L1HOalZIoQ7gm3nk1a84g"
        incentives:
          enabled: true
          contentEvaluator:
            enabled: true
            multipliers:
            - select: [ISSUE_SPECIFICATION]
              relevance: 1
          userExtractor:
            enabled: true
            redeemTask: true
          dataPurge:
            enabled: true
          formattingEvaluator:
            enabled: true
            multipliers:
              - select: [ ISSUE_SPECIFICATION ]
                formattingMultiplier: 3
                symbols:
                  "\\b\\w+\\b": 0.1
                scores:
                  br: 0
                  code: 1
                  p: 1
                  em: 0
                  img: 0
                  strong: 0
                  blockquote: 0
                  h1: 1
                  h2: 1
                  h3: 1
                  h4: 1
                  h5: 1
                  h6: 1
                  a: 1
                  li: 1
                  td: 1
                  hr: 0
              - select: [ ISSUE_AUTHOR ]
                formattingMultiplier: 1
                symbols:
                  "\\b\\w+\\b": 0.2
              - select: [ ISSUE_ASSIGNEE ]
                formattingMultiplier: 0
                symbols:
                  "\\b\\w+\\b": 0
              - select: [ ISSUE_COLLABORATOR ]
                formattingMultiplier: 1
                symbols:
                  "\\b\\w+\\b": 0.1
              - select: [ ISSUE_CONTRIBUTOR ]
                formattingMultiplier: 0.25
                symbols:
                  "\\b\\w+\\b": 0.1
              - select: [ PULL_SPECIFICATION ]
                formattingMultiplier: 0
                symbols:
                  "\\b\\w+\\b": 0
              - select: [ PULL_AUTHOR ]
                formattingMultiplier: 2
                symbols:
                  "\\b\\w+\\b": 0.2
              - select: [ PULL_ASSIGNEE ]
                formattingMultiplier: 1
                symbols:
                  "\\b\\w+\\b": 0.1
              - select: [ PULL_COLLABORATOR ]
                formattingMultiplier: 1
                symbols:
                  "\\b\\w+\\b": 0.1
              - select: [ PULL_CONTRIBUTOR ]
                formattingMultiplier: 0.25
                symbols:
                  "\\b\\w+\\b": 0.1
          permitGeneration:
            enabled: false
          githubComment:
            enabled: true
            post: true
            debug: true
